// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using segParAgustinSantinaqueApi.Dal.Data;

#nullable disable

namespace segParAgustinSantinaqueApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("segParAgustinSantinaqueApi.Dal.Entities.Cancion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscoId")
                        .HasColumnType("int");

                    b.Property<int>("TiempoDuracion")
                        .HasColumnType("int");

                    b.Property<string>("TituloCancion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiscoId");

                    b.ToTable("Canciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiscoId = 1,
                            TiempoDuracion = 360,
                            TituloCancion = "Hells Bells"
                        },
                        new
                        {
                            Id = 2,
                            DiscoId = 1,
                            TiempoDuracion = 250,
                            TituloCancion = "Shoot to Thrill"
                        },
                        new
                        {
                            Id = 3,
                            DiscoId = 2,
                            TiempoDuracion = 300,
                            TituloCancion = "Wanna Be Startin' Somethin'"
                        },
                        new
                        {
                            Id = 4,
                            DiscoId = 2,
                            TiempoDuracion = 600,
                            TituloCancion = "Thriller"
                        },
                        new
                        {
                            Id = 5,
                            DiscoId = 3,
                            TiempoDuracion = 760,
                            TituloCancion = "Stairway to Heaven"
                        },
                        new
                        {
                            Id = 6,
                            DiscoId = 3,
                            TiempoDuracion = 900,
                            TituloCancion = "Black Dog"
                        },
                        new
                        {
                            Id = 7,
                            DiscoId = 4,
                            TiempoDuracion = 384,
                            TituloCancion = "Money"
                        },
                        new
                        {
                            Id = 8,
                            DiscoId = 4,
                            TiempoDuracion = 416,
                            TituloCancion = "Time"
                        },
                        new
                        {
                            Id = 9,
                            DiscoId = 5,
                            TiempoDuracion = 220,
                            TituloCancion = "Go Your Own Way"
                        },
                        new
                        {
                            Id = 10,
                            DiscoId = 5,
                            TiempoDuracion = 257,
                            TituloCancion = "Dreams"
                        },
                        new
                        {
                            Id = 11,
                            DiscoId = 6,
                            TiempoDuracion = 391,
                            TituloCancion = "Hotel California"
                        },
                        new
                        {
                            Id = 12,
                            DiscoId = 6,
                            TiempoDuracion = 286,
                            TituloCancion = "Life in the Fast Lane"
                        },
                        new
                        {
                            Id = 13,
                            DiscoId = 7,
                            TiempoDuracion = 273,
                            TituloCancion = "I Will Always Love You"
                        },
                        new
                        {
                            Id = 14,
                            DiscoId = 7,
                            TiempoDuracion = 275,
                            TituloCancion = "I'm Every Woman"
                        },
                        new
                        {
                            Id = 15,
                            DiscoId = 8,
                            TiempoDuracion = 283,
                            TituloCancion = "Stayin' Alive"
                        },
                        new
                        {
                            Id = 16,
                            DiscoId = 8,
                            TiempoDuracion = 240,
                            TituloCancion = "How Deep Is Your Love"
                        },
                        new
                        {
                            Id = 17,
                            DiscoId = 9,
                            TiempoDuracion = 259,
                            TituloCancion = "Come Together"
                        },
                        new
                        {
                            Id = 18,
                            DiscoId = 9,
                            TiempoDuracion = 182,
                            TituloCancion = "Something"
                        },
                        new
                        {
                            Id = 19,
                            DiscoId = 10,
                            TiempoDuracion = 228,
                            TituloCancion = "Rolling in the Deep"
                        },
                        new
                        {
                            Id = 20,
                            DiscoId = 10,
                            TiempoDuracion = 285,
                            TituloCancion = "Someone Like You"
                        });
                });

            modelBuilder.Entity("segParAgustinSantinaqueApi.Dal.Entities.Disco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Banda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaLanzamiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadesVendidas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Discos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Banda = "AC/DC",
                            FechaLanzamiento = new DateTime(1980, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Rock",
                            Nombre = "Back in Black",
                            SKU = "ABC123",
                            UnidadesVendidas = 50000000
                        },
                        new
                        {
                            Id = 2,
                            Banda = "Michael Jackson",
                            FechaLanzamiento = new DateTime(1982, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Pop",
                            Nombre = "Thriller",
                            SKU = "DEF456",
                            UnidadesVendidas = 66000000
                        },
                        new
                        {
                            Id = 3,
                            Banda = "Led Zeppelin",
                            FechaLanzamiento = new DateTime(1971, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Rock",
                            Nombre = "Led Zeppelin IV",
                            SKU = "GHI789",
                            UnidadesVendidas = 37000000
                        },
                        new
                        {
                            Id = 4,
                            Banda = "Pink Floyd",
                            FechaLanzamiento = new DateTime(1973, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Rock",
                            Nombre = "The Dark Side of the Moon",
                            SKU = "JKL012",
                            UnidadesVendidas = 45000000
                        },
                        new
                        {
                            Id = 5,
                            Banda = "Fleetwood Mac",
                            FechaLanzamiento = new DateTime(1977, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Rock",
                            Nombre = "Rumours",
                            SKU = "MNO345",
                            UnidadesVendidas = 40000000
                        },
                        new
                        {
                            Id = 6,
                            Banda = "Eagles",
                            FechaLanzamiento = new DateTime(1976, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Rock",
                            Nombre = "Hotel California",
                            SKU = "PQR678",
                            UnidadesVendidas = 42000000
                        },
                        new
                        {
                            Id = 7,
                            Banda = "Whitney Houston",
                            FechaLanzamiento = new DateTime(1992, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Soundtrack",
                            Nombre = "The Bodyguard",
                            SKU = "STU901",
                            UnidadesVendidas = 45000000
                        },
                        new
                        {
                            Id = 8,
                            Banda = "Bee Gees",
                            FechaLanzamiento = new DateTime(1977, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Disco",
                            Nombre = "Saturday Night Fever",
                            SKU = "VWX234",
                            UnidadesVendidas = 40000000
                        },
                        new
                        {
                            Id = 9,
                            Banda = "The Beatles",
                            FechaLanzamiento = new DateTime(1969, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Rock",
                            Nombre = "Abbey Road",
                            SKU = "YZA567",
                            UnidadesVendidas = 31000000
                        },
                        new
                        {
                            Id = 10,
                            Banda = "Adele",
                            FechaLanzamiento = new DateTime(2011, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Pop",
                            Nombre = "21",
                            SKU = "BCD890",
                            UnidadesVendidas = 31000000
                        });
                });

            modelBuilder.Entity("segParAgustinSantinaqueApi.Dal.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@mail.com",
                            Name = "John",
                            Password = "123456",
                            UserName = "johndoe"
                        },
                        new
                        {
                            Id = 2,
                            Email = "carla.test@mail.com",
                            Name = "Carla",
                            Password = "2132435465",
                            UserName = "carlatest"
                        });
                });

            modelBuilder.Entity("segParAgustinSantinaqueApi.Dal.Entities.Cancion", b =>
                {
                    b.HasOne("segParAgustinSantinaqueApi.Dal.Entities.Disco", "Disco")
                        .WithMany("Canciones")
                        .HasForeignKey("DiscoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disco");
                });

            modelBuilder.Entity("segParAgustinSantinaqueApi.Dal.Entities.Disco", b =>
                {
                    b.Navigation("Canciones");
                });
#pragma warning restore 612, 618
        }
    }
}
