// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using segParAgustinSantinaqueApi.Dal.Data;

#nullable disable

namespace segParAgustinSantinaqueApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parcial2AgustinSantinaqueWebApi.Dal.Entities.Cancion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscoId")
                        .HasColumnType("int");

                    b.Property<int>("TiempoDuracion")
                        .HasColumnType("int");

                    b.Property<string>("TituloCancion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiscoId");

                    b.ToTable("Canciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiscoId = 1,
                            TiempoDuracion = 360,
                            TituloCancion = "Hells Bells"
                        },
                        new
                        {
                            Id = 2,
                            DiscoId = 1,
                            TiempoDuracion = 250,
                            TituloCancion = "Shoot to Thrill"
                        },
                        new
                        {
                            Id = 3,
                            DiscoId = 2,
                            TiempoDuracion = 300,
                            TituloCancion = "Wanna Be Startin' Somethin'"
                        },
                        new
                        {
                            Id = 4,
                            DiscoId = 2,
                            TiempoDuracion = 600,
                            TituloCancion = "Thriller"
                        },
                        new
                        {
                            Id = 5,
                            DiscoId = 3,
                            TiempoDuracion = 760,
                            TituloCancion = "Stairway to Heaven"
                        },
                        new
                        {
                            Id = 6,
                            DiscoId = 3,
                            TiempoDuracion = 900,
                            TituloCancion = "Black Dog"
                        });
                });

            modelBuilder.Entity("Parcial2AgustinSantinaqueWebApi.Dal.Entities.Disco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Banda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaLanzamiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadesVendidas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Discos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Banda = "AC/DC",
                            FechaLanzamiento = new DateTime(1980, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Rock",
                            Nombre = "Back in Black",
                            SKU = "ABC123",
                            UnidadesVendidas = 50000000
                        },
                        new
                        {
                            Id = 2,
                            Banda = "Michael Jackson",
                            FechaLanzamiento = new DateTime(1982, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Pop",
                            Nombre = "Thriller",
                            SKU = "DEF456",
                            UnidadesVendidas = 66000000
                        },
                        new
                        {
                            Id = 3,
                            Banda = "Led Zeppelin",
                            FechaLanzamiento = new DateTime(1971, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Rock",
                            Nombre = "Led Zeppelin IV",
                            SKU = "GHI789",
                            UnidadesVendidas = 37000000
                        });
                });

            modelBuilder.Entity("Parcial2AgustinSantinaqueWebApi.Dal.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@mail.com",
                            Name = "John",
                            Password = "123456",
                            UserName = "johndoe"
                        },
                        new
                        {
                            Id = 2,
                            Email = "carla.test@mail.com",
                            Name = "Carla",
                            Password = "2132435465",
                            UserName = "carlatest"
                        });
                });

            modelBuilder.Entity("Parcial2AgustinSantinaqueWebApi.Dal.Entities.Cancion", b =>
                {
                    b.HasOne("Parcial2AgustinSantinaqueWebApi.Dal.Entities.Disco", "Disco")
                        .WithMany("Canciones")
                        .HasForeignKey("DiscoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disco");
                });

            modelBuilder.Entity("Parcial2AgustinSantinaqueWebApi.Dal.Entities.Disco", b =>
                {
                    b.Navigation("Canciones");
                });
#pragma warning restore 612, 618
        }
    }
}
